services:
  - type: web
    name: artibot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}