backend:
  name: git-gateway
  branch: main

media_folder: "img/portfolio"
public_folder: "/img/portfolio"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "data/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "string" }
      - { label: "Immagine", name: "image", widget: "image" }